// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.worthto.proto;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_worthto_protobuf_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_worthto_protobuf_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_worthto_protobuf_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_worthto_protobuf_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_worthto_protobuf_PersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_worthto_protobuf_PersonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Person.proto\022\024com.worthto.protobuf\"\035\n\t" +
      "MyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRespons" +
      "e\022\020\n\010realname\030\002 \001(\t\"<\n\016PersonResponse\022\014\n" +
      "\004name\030\003 \001(\t\022\013\n\003age\030\004 \001(\005\022\017\n\007address\030\005 \001(" +
      "\t2\367\002\n\rPersonService\022\\\n\025GetRealNameByUser" +
      "Name\022\037.com.worthto.protobuf.MyRequest\032 ." +
      "com.worthto.protobuf.MyResponse\"\000\022\\\n\017Get" +
      "PersonsByAge\022\037.com.worthto.protobuf.MyRe" +
      "quest\032$.com.worthto.protobuf.PersonRespo" +
      "nse\"\0000\001\022R\n\tSendNames\022\037.com.worthto.proto" +
      "buf.MyRequest\032 .com.worthto.protobuf.MyR" +
      "esponse\"\000(\001\022V\n\013SendPersons\022\037.com.worthto" +
      ".protobuf.MyRequest\032 .com.worthto.protob" +
      "uf.MyResponse\"\000(\0010\001B$\n\021com.worthto.proto" +
      "B\013PersonProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_worthto_protobuf_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_worthto_protobuf_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_worthto_protobuf_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_worthto_protobuf_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_worthto_protobuf_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_worthto_protobuf_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_worthto_protobuf_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_worthto_protobuf_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_worthto_protobuf_PersonResponse_descriptor,
        new String[] { "Name", "Age", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
