// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.worthto.proto;

public interface PersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.worthto.protobuf.PersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 4;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string address = 5;</code>
   * @return The address.
   */
  String getAddress();
  /**
   * <code>string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
